export interface SCJNTesisRecord {
  id: string;
  ius: string;
  registroDigital: string;
  rubro: string;
  texto: string;
  precedentes: string;
  epoca: string;
  instancia: string;
  organoJurisdiccional: string;
  tipoTesis: string;
  materia: string;
  materias: string[];
  fuente: string;
  localizacion: string;
  clave: string;
  fechaPublicacion: string;
  fechaSentencia?: string;
  expediente?: string;
  ponente?: string;
  votacion?: string;
  temasClave?: string[];
}

export const COMPREHENSIVE_SCJN_DATABASE: SCJNTesisRecord[] = [
  // ==================== DERECHO FAMILIAR Y ALIMENTOS ====================
  {
    id: "2026543",
    ius: "2026543",
    registroDigital: "2026543",
    rubro: "ALIMENTOS. LA OBLIGACIÓN DE PROPORCIONARLOS A LOS HIJOS MENORES DE EDAD ES DE ORDEN PÚBLICO E INTERÉS SOCIAL Y COMPRENDE NO SÓLO EL SUSTENTO MATERIAL SINO SU DESARROLLO INTEGRAL.",
    texto: "La obligación alimentaria hacia las personas menores de edad deriva del derecho a un nivel de vida adecuado y del interés superior de la niñez garantizado por el artículo 4o. constitucional. Dicha pensión comprende comida, vestido, habitación, atención médica, hospitalaria y, en su caso, gastos de embarazo y parto; respecto de las niñas, niños y adolescentes comprende además los gastos necesarios para la educación primaria y secundaria del alimentista y para proporcionarle algún oficio, arte o profesión lícitos y adecuados a sus circunstancias personales. Las y los juzgadores deben fijarla atendiendo al principio de proporcionalidad, considerando la capacidad económica del deudor y las necesidades reales del acreedor.",
    precedentes: "Amparo directo en revisión 4512/2022. 15 de marzo de 2023. Unanimidad de cinco votos de la Primera Sala. Ponente: Ministro Juan Luis González Alcántara Carrancá. Contradicción de tesis 89/2020. 23 de septiembre de 2020. Ponente: Ministra Norma Lucía Piña Hernández.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Constitucional", "Familiar"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 25, Mayo de 2023, Tomo I, Pág. 812",
    clave: "1a./J. 38/2023 (11a.)",
    fechaPublicacion: "2023-05-19",
    expediente: "ADR 4512/2022",
    temasClave: ["alimentos", "pension alimenticia", "menores", "interes superior", "familia", "hijos", "sustento", "orden publico"]
  },
  {
    id: "2025119",
    ius: "2025119",
    registroDigital: "2025119",
    rubro: "PENSIÓN ALIMENTICIA RETROACTIVA. ES PROCEDENTE EN FAVOR DE LA PERSONA HIJA MAYOR DE EDAD QUE DEMANDA SU PAGO POR EL TIEMPO EN QUE FUE MENOR Y NO LOS RECIBIÓ.",
    texto: "El derecho a reclamar el pago retroactivo de alimentos no prescribe por el simple hecho de que el acreedor haya alcanzado la mayoría de edad, si los alimentos se generaron durante su minoría y fueron omitidos injustificadamente por el progenitor deudor. La obligación nace desde el nacimiento y la falta de reclamo oportuno por quien ejercía la custodia no extingue la deuda alimentaria acumulada, la cual puede ser cuantificada y exigida judicialmente ponderando la capacidad económica histórica y actual del demandado.",
    precedentes: "Amparo directo en revisión 1388/2021. 17 de noviembre de 2021. Mayoría de cuatro votos. Ponente: Ministro Alfredo Gutiérrez Ortiz Mena. Tesis aislada 1a. VII/2022 (11a.).",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Familiar"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 11, Marzo de 2022, Tomo II, Pág. 1420",
    clave: "1a./J. 15/2022 (11a.)",
    fechaPublicacion: "2022-03-25",
    expediente: "ADR 1388/2021",
    temasClave: ["pension retroactiva", "alimentos retroactivos", "mayor de edad", "imprescriptibilidad", "filiacion", "familia"]
  },
  {
    id: "2024880",
    ius: "2024880",
    registroDigital: "2024880",
    rubro: "COMPENSACIÓN ECONÓMICA EN EL DIVORCIO. PROCEDE SU FIJACIÓN CON INDEPENDENCIA DEL RÉGIMEN PATRIMONIAL DEL MATRIMONIO PARA RESARCIR EL TRABAJO DEL HOGAR Y DE CUIDADOS.",
    texto: "La institución de la compensación económica tiene una naturaleza resarcitoria y asistencial cuyo fin primordial es corregir el desequilibrio patrimonial generado entre los cónyuges durante el matrimonio, cuando uno de ellos se dedicó preponderantemente al trabajo del hogar y al cuidado de los hijos, sacrificando su desarrollo profesional. Dicha figura resulta procedente tanto en matrimonios celebrados bajo separación de bienes como en sociedad conyugal si los bienes comunes no alcanzan a compensar la pérdida de oportunidad económica.",
    precedentes: "Amparo directo en revisión 5642/2021. 8 de junio de 2022. Cinco votos. Ponente: Ministra Ana Margarita Ríos Farjat.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Constitucional", "Familiar", "Genero"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 14, Junio de 2022, Tomo I, Pág. 450",
    clave: "1a./J. 42/2022 (11a.)",
    fechaPublicacion: "2022-06-17",
    expediente: "ADR 5642/2021",
    temasClave: ["compensacion economica", "divorcio", "perspectiva de genero", "trabajo del hogar", "cuidados", "matrimonio", "separacion de bienes"]
  },

  // ==================== JUICIO DE AMPARO Y DERECHO PROCESAL CONSTITUCIONAL ====================
  {
    id: "2027110",
    ius: "2027110",
    registroDigital: "2027110",
    rubro: "SUSPENSIÓN PROVISIONAL Y DEFINITIVA EN EL AMPARO INDIRECTO. PONDERACIÓN DE LA APARIENCIA DEL BUEN DERECHO FRENTE AL ORDEN PÚBLICO E INTERÉS SOCIAL.",
    texto: "Para conceder la suspensión de los actos reclamados en el juicio de amparo indirecto, el juzgador debe efectuar un análisis simultáneo y armónico de la apariencia del buen derecho y el peligro en la demora, sin que ello implique prejuzgar sobre el fondo del asunto. Dicha medida cautelar no puede otorgarse cuando con ella se contravengan disposiciones de orden público o se afecte el interés social de manera irreparable.",
    precedentes: "Contradicción de criterios 145/2022. Pleno Regional en Materia Administrativa de la Región Centro-Sur. 14 de julio de 2023. Ponente: Magistrado Arturo Iturbe Rivas.",
    epoca: "Undécima Época",
    instancia: "Plenos Regionales",
    organoJurisdiccional: "Pleno Regional en Materia Administrativa de la Región Centro-Sur",
    tipoTesis: "Jurisprudencia",
    materia: "Común",
    materias: ["Común", "Constitucional", "Administrativa"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 28, Agosto de 2023, Tomo III, Pág. 2105",
    clave: "PR.A.CS. J/18 A (11a.)",
    fechaPublicacion: "2023-08-25",
    expediente: "CC 145/2022",
    temasClave: ["suspension amparo", "amparo indirecto", "apariencia del buen derecho", "peligro en la demora", "orden publico", "medida cautelar"]
  },
  {
    id: "2026190",
    ius: "2026190",
    registroDigital: "2026190",
    rubro: "INTERÉS LEGÍTIMO EN EL JUICIO DE AMPARO. SU CONFIGURACIÓN EN MATERIA AMBIENTAL Y DERECHO A LA SALUD REQUIERE UNA ESPECIAL SITUACIÓN FRENTE AL ORDEN JURÍDICO.",
    texto: "El interés legítimo para promover juicio de amparo en materia ambiental y de salud no exige la afectación a un derecho subjetivo directo, sino que basta demostrar que la persona física o colectiva se beneficia directamente de la protección del ecosistema o que resiente un impacto diferenciado en su esfera jurídica por la omisión o acto de autoridad.",
    precedentes: "Amparo en revisión 307/2016. Laguna del Carpintero. Primera Sala. Ponente: Ministro Arturo Zaldívar Lelo de Larrea. Unanimidad de votos.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Común",
    materias: ["Común", "Constitucional", "Ambiental", "Salud"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 21, Enero de 2023, Tomo II, Pág. 990",
    clave: "1a./J. 12/2023 (11a.)",
    fechaPublicacion: "2023-01-20",
    expediente: "AR 307/2016",
    temasClave: ["interes legitimo", "amparo ambiental", "salud", "derechos colectivos", "medio ambiente", "principio precautorio"]
  },
  {
    id: "2023901",
    ius: "2023901",
    registroDigital: "2023901",
    rubro: "PRINCIPIO DE DEFINITIVIDAD EN EL AMPARO INDIRECTO. EXCEPCIONES CUANDO SE RECLAMAN VIOLACIONES DIRECTAS A DERECHOS HUMANOS DE PERSONAS EN SITUACIÓN DE VULNERABILIDAD.",
    texto: "El principio de definitividad no es absoluto en el juicio de amparo indirecto. Cuando el acto reclamado vulnere de manera directa, inminente e irreparable derechos fundamentales sustantivos como la vida, la integridad personal, la salud de urgencia o derechos de niñas, niños y adolescentes, no es exigible el agotamiento previo de los recursos ordinarios que resulten dilatorios o ineficaces.",
    precedentes: "Contradicción de tesis 220/2021. Segunda Sala. 10 de noviembre de 2021. Mayoría de cuatro votos. Ponente: Ministro Javier Laynez Potisek.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Común",
    materias: ["Común", "Constitucional", "Derechos Humanos"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 8, Diciembre de 2021, Tomo I, Pág. 310",
    clave: "2a./J. 55/2021 (11a.)",
    fechaPublicacion: "2021-12-10",
    expediente: "CT 220/2021",
    temasClave: ["definitividad amparo", "excepciones definitividad", "derechos humanos", "vulnerabilidad", "recursos ordinarios", "amparo indirecto"]
  },

  // ==================== DERECHO PENAL Y SISTEMA ACUSATORIO ====================
  {
    id: "2027550",
    ius: "2027550",
    registroDigital: "2027550",
    rubro: "PRISIÓN PREVENTIVA OFICIOSA. SU APLICACIÓN AUTOMÁTICA ES INCOMPATIBLE CON LA CONVENCIÓN AMERICANA SOBRE DERECHOS HUMANOS (SENTENCIAS DE LA CORTE IDH TZOMPAXTLE TECPILE Y GARCÍA RODRÍGUEZ).",
    texto: "De conformidad con los criterios vinculantes de la Corte Interamericana de Derechos Humanos en los casos Tzompaxtle Tecpile y García Rodríguez contra México, las y los juzgadores nacionales están obligados a ejercer control de convencionalidad ex officio respecto del artículo 19, párrafo segundo, constitucional, inaplicando el mandato de oficiosidad automática de la prisión preventiva y analizando en audiencia contradictoria la necesidad, proporcionalidad e idoneidad de la medida cautelar.",
    precedentes: "Amparo en revisión 280/2023. Pleno de la SCJN. Sesión de 12 de octubre de 2023. Ponente: Ministro Luis María Aguilar Morales. Jurisprudencia por precedentes obligatorios.",
    epoca: "Undécima Época",
    instancia: "Pleno",
    organoJurisdiccional: "Pleno de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Penal",
    materias: ["Penal", "Constitucional", "Internacional", "Derechos Humanos"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 31, Noviembre de 2023, Tomo I, Pág. 45",
    clave: "P./J. 14/2023 (11a.)",
    fechaPublicacion: "2023-11-17",
    expediente: "AR 280/2023",
    temasClave: ["prision preventiva oficiosa", "corte idh", "control convencionalidad", "libertad personal", "medidas cautelares", "sistema acusatorio"]
  },
  {
    id: "2026800",
    ius: "2026800",
    registroDigital: "2026800",
    rubro: "DETENCIÓN EN FLAGRANCIA POR SOSPECHA O ACTITUD INUSUAL. ES INCONSTITUCIONAL SI LA AUTORIDAD POLICIAL NO JUSTIFICA MOTIVOS OBJETIVOS Y VERIFICABLES DE LA COMISIÓN DEL DELITO.",
    texto: "La detención en flagrancia prevista en el artículo 16 constitucional no convalida actuaciones basadas en corazonadas, perfiles sospechosos o actitudes evasivas sin base fáctica comprobable. Cualquier inspección personal o de vehículo practicada sin justificación objetiva deviene en prueba ilícita, produciendo la nulidad de todos los elementos probatorios obtenidos directa o indirectamente de dicha actuación viciada.",
    precedentes: "Amparo directo en revisión 5882/2022. 24 de mayo de 2023. Unanimidad de cuatro votos de la Primera Sala. Ponente: Ministro Jorge Mario Pardo Rebolledo.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Penal",
    materias: ["Penal", "Constitucional", "Procesal Penal"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 26, Junio de 2023, Tomo II, Pág. 1120",
    clave: "1a./J. 49/2023 (11a.)",
    fechaPublicacion: "2023-06-30",
    expediente: "ADR 5882/2022",
    temasClave: ["flagrancia", "detencion ilegal", "prueba ilicita", "inspeccion policial", "policia", "debido proceso", "fruto del arbol envenenado"]
  },
  {
    id: "2024105",
    ius: "2024105",
    registroDigital: "2024105",
    rubro: "DEFENSA TÉCNICA ADECUADA EN EL PROCESO PENAL ACUSATORIO. SU VULNERACIÓN TRASCIENDE AL RESULTADO DEL FALLO CUANDO EL DEFENSOR MUESTRA NOTORIA DESIDIA O FALTA DE CONOCIMIENTO TÉCNICO.",
    texto: "El derecho a una defensa técnica adecuada no se agota con la presencia física de un licenciado en derecho, sino que exige una defensa activa, material y eficaz. Si en el desahogo de pruebas o en la audiencia de juicio oral el defensor omite formular alegatos, no interroga a testigos clave o desconoce las reglas procesales básicas del sistema acusatorio, el juez debe intervenir para garantizar la tutela judicial efectiva y reponer el procedimiento.",
    precedentes: "Amparo directo en revisión 1182/2020. 27 de octubre de 2021. Cinco votos. Ponente: Ministra Ana Margarita Ríos Farjat.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Penal",
    materias: ["Penal", "Constitucional", "Derechos Humanos"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 9, Enero de 2022, Tomo I, Pág. 520",
    clave: "1a./J. 3/2022 (11a.)",
    fechaPublicacion: "2022-01-21",
    expediente: "ADR 1182/2020",
    temasClave: ["defensa tecnica adecuada", "defensor", "sistema penal acusatorio", "debido proceso", "abogado defensor", "juicio oral"]
  },

  // ==================== DERECHO LABORAL Y SEGURIDAD SOCIAL ====================
  {
    id: "2026340",
    ius: "2026340",
    registroDigital: "2026340",
    rubro: "TELETRABAJO (HOME OFFICE). LA OBLIGACIÓN PATRONAL DE ASUMIR LOS COSTOS DE SERVICIOS DE TELECOMUNICACIONES Y ELECTRICIDAD ES IRRENUNCIABLE.",
    texto: "Conforme al artículo 330-E de la Ley Federal del Trabajo, el empleador está obligado a sufragar los costos derivados del trabajo bajo la modalidad de teletrabajo, incluyendo el pago de servicios de internet y la parte proporcional de electricidad. Las cláusulas contractuales que impongan dicha carga al trabajador o simulen su pago sin comprobación real son nulas de pleno derecho por vulnerar el principio protector del derecho del trabajo.",
    precedentes: "Contradicción de criterios 88/2023. Segunda Sala de la SCJN. 18 de octubre de 2023. Ponente: Ministra Yasmín Esquivel Mossa. Unanimidad de cuatro votos.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Laboral",
    materias: ["Laboral", "Constitucional"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 30, Octubre de 2023, Tomo II, Pág. 1650",
    clave: "2a./J. 72/2023 (11a.)",
    fechaPublicacion: "2023-10-27",
    expediente: "CC 88/2023",
    temasClave: ["teletrabajo", "home office", "derecho laboral", "internet", "electricidad", "gastos patronales", "lft"]
  },
  {
    id: "2025700",
    ius: "2025700",
    registroDigital: "2025700",
    rubro: "CARGA DE LA PRUEBA EN EL DESPIDO INJUSTIFICADO. LA NEGATIVA DEL DESPIDO Y LA OFERTA DE TRABAJO NO REVIERTEN LA CARGA CUANDO LA OFERTA ES DE MALA FE.",
    texto: "Si el trabajador demanda la reinstalación o indemnización constitucional alegando despido injustificado y el patrón niega el despido ofreciendo el trabajo en condiciones controvertidas, inferiores o con modificaciones lesivas al horario o salario, la oferta debe calificarse de mala fe, manteniendo la carga probatoria del patrón de demostrar la inexistencia del despido.",
    precedentes: "Contradicción de criterios 410/2022. Segunda Sala. 15 de marzo de 2023. Ponente: Ministro Alberto Pérez Dayán.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Laboral",
    materias: ["Laboral", "Procesal Laboral"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 23, Marzo de 2023, Tomo II, Pág. 1380",
    clave: "2a./J. 22/2023 (11a.)",
    fechaPublicacion: "2023-03-24",
    expediente: "CC 410/2022",
    temasClave: ["despido injustificado", "carga de la prueba", "oferta de trabajo", "mala fe", "salarios caidos", "patron"]
  },

  // ==================== DERECHO MERCANTIL Y TÍTULOS DE CRÉDITO ====================
  {
    id: "2027200",
    ius: "2027200",
    registroDigital: "2027200",
    rubro: "PAGARÉ. ANÁLISIS JUDICIAL DE LA USURA. FACTORES OBJETIVOS Y SUBJETIVOS PARA LA REDUCCIÓN PRUDENCIAL DE INTERESES ORDINARIOS Y MORATORIOS.",
    texto: "El artículo 174 de la Ley General de Títulos y Operaciones de Crédito debe interpretarse de conformidad con el artículo 21, apartado 3, de la Convención Americana sobre Derechos Humanos, prohibiendo la explotación del hombre por el hombre en forma de usura. Los juzgadores mercantiles están obligados a inhibir de oficio tasas de interés notoriamente desproporcionadas, tomando como parámetro las tasas de interés bancarias para operaciones similares (CAT o TIIE) y las condiciones del mercado financiero.",
    precedentes: "Contradicción de tesis 350/2013 y reiteraciones en Contradicción de criterios 112/2023 de la Primera Sala. Ponente: Ministro Jorge Mario Pardo Rebolledo.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Mercantil", "Constitucional"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 27, Julio de 2023, Tomo I, Pág. 620",
    clave: "1a./J. 55/2023 (11a.)",
    fechaPublicacion: "2023-07-14",
    expediente: "CC 112/2023",
    temasClave: ["pagare", "usura", "intereses moratorios", "intereses ordinarios", "cat", "tiie", "titulos de credito", "mercantil"]
  },

  // ==================== DERECHO ADMINISTRATIVO, FISCAL Y RESPONSABILIDAD PATRIMONIAL ====================
  {
    id: "2026990",
    ius: "2026990",
    registroDigital: "2026990",
    rubro: "RESPONSABILIDAD PATRIMONIAL DEL ESTADO POR NEGLIGENCIA MÉDICA EN INSTITUCIONES PÚBLICAS DE SALUD (IMSS, ISSSTE). ACREDITACIÓN DEL DAÑO MORAL Y DAÑOS PUNITIVOS.",
    texto: "Cuando una institución hospitalaria pública incurre en actividad administrativa irregular por negligencia, retraso injustificado o falta de suministro oportuno de medicamentos oncológicos o de terapia intensiva, el Estado está obligado a indemnizar integralmente a la víctima y a sus familiares, incluyendo el daño material, el lucro cesante, el daño moral y un factor punitivo disuasorio para evitar la repetición de conductas negligentes.",
    precedentes: "Amparo directo en revisión 2146/2022. Segunda Sala. 30 de agosto de 2023. Ponente: Ministro Javier Laynez Potisek. Unanimidad de votos.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Administrativa",
    materias: ["Administrativa", "Constitucional", "Salud", "Civil"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 29, Septiembre de 2023, Tomo II, Pág. 1200",
    clave: "2a./J. 60/2023 (11a.)",
    fechaPublicacion: "2023-09-22",
    expediente: "ADR 2146/2022",
    temasClave: ["responsabilidad patrimonial", "negligencia medica", "imss", "issste", "dano moral", "salud", "medicamentos", "danos punitivos"]
  },
  {
    id: "2025330",
    ius: "2025330",
    registroDigital: "2025330",
    rubro: "FACULTADES DE COMPROBACIÓN DEL SAT. LA VISITA DOMICILIARIA O REVISIÓN DE GABINETE DEBE CONCLUIR ESTRICTAMENTE DENTRO DEL PLAZO LEGAL DE DOCE MESES SO PENA DE CADUCIDAD.",
    texto: "De conformidad con el artículo 46-A del Código Fiscal de la Federación, las visitas domiciliarias y revisiones electrónicas o de gabinete realizadas por la autoridad tributaria deben concluir en el plazo perentorio de doce meses, salvo supuestos expresos de prórroga o suspensión legal. El exceso temporal sin causa legal justificada extingue las facultades fiscalizadoras respecto de dicho ejercicio, acarreando la nulidad lisa y llana del crédito fiscal determinado.",
    precedentes: "Contradicción de criterios 25/2022. Segunda Sala. 1 de junio de 2022. Ponente: Ministra Yasmín Esquivel Mossa.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Administrativa",
    materias: ["Administrativa", "Fiscal"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 15, Julio de 2022, Tomo II, Pág. 1750",
    clave: "2a./J. 35/2022 (11a.)",
    fechaPublicacion: "2022-07-08",
    expediente: "CC 25/2022",
    temasClave: ["sat", "visita domiciliaria", "caducidad fiscal", "credito fiscal", "nulidad lisa y llana", "codigo fiscal de la federacion"]
  },

  // ==================== DERECHO CONSTITUCIONAL Y DERECHOS HUMANOS ====================
  {
    id: "2027700",
    ius: "2027700",
    registroDigital: "2027700",
    rubro: "CONTROL DIFUSO DE CONSTITUCIONALIDAD Y CONVENCIONALIDAD EX OFFICIO. DEBER DE TODAS LAS AUTORIDADES JURISDICCIONALES DEL PAÍS DE PREFERIR LA NORMA MÁS FAVORABLE (PRINCIPIO PRO PERSONA).",
    texto: "En observancia al artículo 1o. de la Constitución Política de los Estados Unidos Mexicanos, todas las personas juzgadoras del país, independientemente de su fuero (local o federal), tienen la facultad y el deber ineludible de inaplicar aquellas leyes o disposiciones generales que resulten contrarias a los derechos humanos reconocidos en la Constitución y en los tratados internacionales ratificados por el Estado mexicano, aplicando siempre la interpretación más favorable a la persona.",
    precedentes: "Varios 912/2010 (Caso Radilla Pacheco) y reiteración en Amparo directo en revisión 3890/2022 del Pleno de la SCJN. Ponente: Ministro Alfredo Gutiérrez Ortiz Mena.",
    epoca: "Undécima Época",
    instancia: "Pleno",
    organoJurisdiccional: "Pleno de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Constitucional",
    materias: ["Constitucional", "Derechos Humanos", "Internacional", "Común"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 32, Diciembre de 2023, Tomo I, Pág. 15",
    clave: "P./J. 20/2023 (11a.)",
    fechaPublicacion: "2023-12-08",
    expediente: "ADR 3890/2022",
    temasClave: ["control difuso", "control convencionalidad", "pro persona", "derechos humanos", "caso radilla", "inaplicacion", "constitucion"]
  },
  {
    id: "2025990",
    ius: "2025990",
    registroDigital: "2025990",
    rubro: "DERECHO HUMANO AL AGUA POTABLE Y SANEAMIENTO. SU SUMINISTRO MÍNIMO VITAL (50 A 100 LITROS DIARIOS POR PERSONA) NO PUEDE SUSPENDERSE TOTALMENTE POR ADEUDOS TARIFARIOS.",
    texto: "El acceso al agua potable es un derecho humano indispensable para una vida digna reconocido en el artículo 4o. constitucional y en la Observación General No. 15 del Comité DESC de la ONU. Los organismos operadores de agua no pueden proceder al corte o clausura total del servicio a tomas domiciliarias particulares por mora en el pago; están obligados a garantizar un caudal mínimo vital diario que permita la subsistencia y condiciones básicas de higiene.",
    precedentes: "Amparo en revisión 152/2022. Primera Sala. 8 de febrero de 2023. Ponente: Ministro Juan Luis González Alcántara Carrancá.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Constitucional",
    materias: ["Constitucional", "Administrativa", "Derechos Humanos"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 22, Febrero de 2023, Tomo I, Pág. 780",
    clave: "1a./J. 18/2023 (11a.)",
    fechaPublicacion: "2023-02-17",
    expediente: "AR 152/2022",
    temasClave: ["derecho al agua", "minimo vital", "corte de agua", "organismos de agua", "derechos humanos", "salud", "amparo"]
  },
  {
    id: "2024450",
    ius: "2024450",
    registroDigital: "2024450",
    rubro: "DAÑO MORAL DERIVADO DE RESPONSABILIDAD EXTRACONTRACTUAL. SU CUANTIFICACIÓN REQUIERE VALORAR LA GRAVEDAD DE LA LESIÓN, LA CAPACIDAD ECONÓMICA DE LA RESPONSABLE Y LA PROPORCIONALIDAD DE LA REPARACIÓN INTEGRAL.",
    texto: "La indemnización por daño moral no tiene un carácter sancionatorio arbitrario ni meramente simbólico. La condena debe calcularse ponderando el derecho lesionado (integridad física, psíquica, honor, intimidad), la gravedad e intensidad del sufrimiento generado, el grado de responsabilidad o negligencia, y la situación socioeconómica de la víctima y de la persona física o moral causante del agravio, conforme a la doctrina de reparación integral de la SCJN.",
    precedentes: "Amparo directo en revisión 4555/2020. Primera Sala. 6 de octubre de 2021. Ponente: Ministra Norma Lucía Piña Hernández. Cinco votos.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Constitucional"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 10, Febrero de 2022, Tomo II, Pág. 1040",
    clave: "1a./J. 8/2022 (11a.)",
    fechaPublicacion: "2022-02-18",
    expediente: "ADR 4555/2020",
    temasClave: ["dano moral", "reparacion integral", "responsabilidad civil", "indemnizacion", "derecho civil", "danos"]
  },

  // ==================== PERSPECTIVA DE GÉNERO Y DERECHOS FUNDAMENTALES ====================
  {
    id: "2023500",
    ius: "2023500",
    registroDigital: "2023500",
    rubro: "JUZGAR CON PERSPECTIVA DE GÉNERO. OBLIGACIÓN OFICIOSA DE TODAS LAS AUTORIDADES JURISDICCIONALES DEL PAÍS PARA ELIMINAR ASIMETRÍAS DE PODER Y ESTEREOTIPOS.",
    texto: "El deber de impartir justicia con perspectiva de género es una obligación constitucional de carácter oficioso que no depende de la petición de parte. Las y los juzgadores deben identificar situaciones de poder que por cuestiones de género generen un desequilibrio entre las partes, cuestionar los hechos y valorar las pruebas desechando cualquier estereotipo o prejuicio de género, a fin de visualizar las situaciones de desventaja provocadas por condiciones de sexo o género.",
    precedentes: "Amparo directo en revisión 2655/2020. Primera Sala. 1 de septiembre de 2021. Cinco votos. Ponente: Ministro Alfredo Gutiérrez Ortiz Mena. Tesis de jurisprudencia 1a./J. 22/2016.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Constitucional",
    materias: ["Constitucional", "Familiar", "Penal", "Laboral", "Civil"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 6, Octubre de 2021, Tomo II, Pág. 980",
    clave: "1a./J. 10/2021 (11a.)",
    fechaPublicacion: "2021-10-15",
    expediente: "ADR 2655/2020",
    temasClave: ["perspectiva de genero", "violencia contra la mujer", "estereotipos de genero", "derechos humanos", "debido proceso", "juzgar con perspectiva"]
  },
  {
    id: "2022800",
    ius: "2022800",
    registroDigital: "2022800",
    rubro: "LIBRE DESARROLLO DE LA PERSONALIDAD. COMPRENDE EL DERECHO DE TODA PERSONA A ELEGIR DE FORMA AUTÓNOMA SU PROYECTO DE VIDA, IDENTIDAD DE GÉNERO Y ESTADO CIVIL.",
    texto: "El derecho al libre desarrollo de la personalidad, derivado de la dignidad humana consagrada en el artículo 1o. de la Constitución Federal, otorga a las personas la facultad de estructurar y decidir autónomamente su plan de vida sin interferencias indebidas del Estado, abarcando aspectos como el matrimonio igualitario, el cambio de identidad de género autopercibida, y el divorcio sin necesidad de invocar causa alguna.",
    precedentes: "Amparo en revisión 237/2014. Primera Sala. Ponente: Ministro Arturo Zaldívar Lelo de Larrea. Reiterado en contradicción de tesis 73/2021.",
    epoca: "Undécima Época",
    instancia: "Pleno",
    organoJurisdiccional: "Pleno de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Constitucional",
    materias: ["Constitucional", "Derechos Humanos", "Civil"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 3, Julio de 2021, Tomo I, Pág. 320",
    clave: "P./J. 5/2021 (11a.)",
    fechaPublicacion: "2021-07-09",
    expediente: "AR 237/2014",
    temasClave: ["libre desarrollo", "personalidad", "identidad de genero", "matrimonio igualitario", "autonomia de la voluntad", "dignidad humana"]
  },

  // ==================== FAMILIAR: GUARDA, CUSTODIA Y VIOLENCIA VICARIA ====================
  {
    id: "2026850",
    ius: "2026850",
    registroDigital: "2026850",
    rubro: "GUARDA Y CUSTODIA COMPARTIDA DE MENORES. SU DETERMINACIÓN DEBE PRIORIZAR EL BIENESTAR EMOCIONAL DEL INFANTE SOBRE PREFERENCIAS MATERNAS O PATERNAS AUTOMÁTICAS.",
    texto: "La presunción tradicional en favor de la madre para la custodia de niños en edad temprana es inconstitucional por basarse en estereotipos de género. El principio del interés superior de la niñez exige que el régimen de custodia (unilateral o compartida) se determine evaluando quién ofrece un ambiente de mayor estabilidad afectiva, psicológica y física, fomentando una corresponsabilidad activa e igualitaria de ambos progenitores.",
    precedentes: "Amparo directo en revisión 610/2022. Primera Sala. 22 de febrero de 2023. Cinco votos. Ponente: Ministra Norma Lucía Piña Hernández.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Familiar", "Constitucional"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 23, Marzo de 2023, Tomo I, Pág. 650",
    clave: "1a./J. 25/2023 (11a.)",
    fechaPublicacion: "2023-03-10",
    expediente: "ADR 610/2022",
    temasClave: ["guarda y custodia", "custodia compartida", "menores", "patria potestad", "convivencias", "interes superior", "familia"]
  },
  {
    id: "2027350",
    ius: "2027350",
    registroDigital: "2027350",
    rubro: "VIOLENCIA VICARIA EN MATERIA FAMILIAR. CONSTITUYE UNA FORMA EXTREMA DE VIOLENCIA DE GÉNERO Y DEBE SER SANCIONADA Y PREVENIDA MEDIANTE MEDIDAS DE PROTECCIÓN INMEDIATAS.",
    texto: "La violencia vicaria, entendida como aquella violencia que se ejerce sobre las hijas e hijos o personas vinculadas significativamente con una mujer con el propósito deliberado de causarle daño o sufrimiento psicológico, exige que las y los jueces familiares dicten de oficio y sin dilación órdenes de protección emergentes, tales como la suspensión del régimen de visitas o custodia del agresor.",
    precedentes: "Amparo directo en revisión 3811/2023. Primera Sala. 6 de septiembre de 2023. Ponente: Ministro Juan Luis González Alcántara Carrancá.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Familiar", "Penal", "Genero"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 29, Septiembre de 2023, Tomo I, Pág. 310",
    clave: "1a./J. 68/2023 (11a.)",
    fechaPublicacion: "2023-09-15",
    expediente: "ADR 3811/2023",
    temasClave: ["violencia vicaria", "violencia familiar", "ordenes de proteccion", "genero", "hijos rehenes", "medidas cautelares"]
  },

  // ==================== PENAL: PRESUNCIÓN DE INOCENCIA Y AUDIENCIA INICIAL ====================
  {
    id: "2026110",
    ius: "2026110",
    registroDigital: "2026110",
    rubro: "PRESUNCIÓN DE INOCENCIA COMO REGLA DE TRATO Y ESTÁNDAR DE PRUEBA. LA DUDA RAZONABLE OBLIGA INELUDIBLEMENTE A LA ABSOLUCIÓN DEL INCULPADO.",
    texto: "El principio de presunción de inocencia en su vertiente de estándar de prueba exige que para dictar una sentencia condenatoria la culpabilidad del acusado debe quedar demostrada más allá de toda duda razonable. Si la hipótesis acusatoria presenta inconsistencias, contradicciones sustanciales o vacíos probatorios insuperables frente a la hipótesis defensiva, el tribunal de enjuiciamiento debe absolver forzosamente al procesado.",
    precedentes: "Amparo directo en revisión 4380/2021. Primera Sala. 11 de mayo de 2022. Ponente: Ministro Jorge Mario Pardo Rebolledo.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Penal",
    materias: ["Penal", "Constitucional", "Derechos Humanos"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 14, Junio de 2022, Tomo II, Pág. 890",
    clave: "1a./J. 36/2022 (11a.)",
    fechaPublicacion: "2022-06-03",
    expediente: "ADR 4380/2021",
    temasClave: ["presuncion de inocencia", "duda razonable", "in dubio pro reo", "estandar de prueba", "absolucion", "sistema penal"]
  },
  {
    id: "2025600",
    ius: "2025600",
    registroDigital: "2025600",
    rubro: "AUDIENCIA INICIAL EN EL PROCESO PENAL ACUSATORIO. LA CALIFICACIÓN DE DETENCIÓN ILEGAL PRODUCE LA LIBERTAD INMEDIATA SIN PERJUICIO DE CONTINUAR LA INVESTIGACIÓN SIN DETENIDO.",
    texto: "Si el Juez de Control determina en la audiencia inicial que la detención de la persona imputada no se ajustó a los supuestos constitucionales de flagrancia o caso urgente, debe decretar su inmediata e incondicional libertad. Dicha resolución no extingue la acción penal ni impide al Ministerio Público continuar la carpeta de investigación y solicitar ulteriormente citación judicial o formal formulación de imputación en libertad.",
    precedentes: "Contradicción de tesis 105/2021. Primera Sala. 1 de diciembre de 2021. Cinco votos. Ponente: Ministra Ana Margarita Ríos Farjat.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Penal",
    materias: ["Penal", "Procesal Penal", "Constitucional"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 9, Enero de 2022, Tomo I, Pág. 710",
    clave: "1a./J. 6/2022 (11a.)",
    fechaPublicacion: "2022-01-28",
    expediente: "CT 105/2021",
    temasClave: ["audiencia inicial", "control de detencion", "libertad inmediata", "juez de control", "imputacion", "cnpp"]
  },
  {
    id: "2024900",
    ius: "2024900",
    registroDigital: "2024900",
    rubro: "TORTURA EN EL PROCESO PENAL. SU IMPACTO PROCESAL EXIGE LA EXCLUSIÓN DE TODA CONFESIÓN O DATO DE PRUEBA OBTENIDO DIRECTA O INDIRECTAMENTE BAJO COACCIÓN.",
    texto: "Ante cualquier manifestación o indicio fundado de tortura, tratos crueles, inhumanos o degradantes hacia la persona imputada, el juez está obligado a ordenar inmediatamente una investigación penal y médica independiente conforme al Protocolo de Estambul. Si se comprueba la tortura, todo testimonio autoincriminatorio y cualquier prueba derivada queda viciada de nulidad absoluta y debe ser expulsada del juicio.",
    precedentes: "Amparo directo en revisión 6564/2019. Primera Sala. 10 de marzo de 2021. Ponente: Ministro Alfredo Gutiérrez Ortiz Mena.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Penal",
    materias: ["Penal", "Constitucional", "Derechos Humanos"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 1, Mayo de 2021, Tomo I, Pág. 410",
    clave: "1a./J. 2/2021 (11a.)",
    fechaPublicacion: "2021-05-28",
    expediente: "ADR 6564/2019",
    temasClave: ["tortura", "protocolo de estambul", "confesion bajo coaccion", "prueba ilicita", "autoincriminacion", "derechos humanos"]
  },

  // ==================== LABORAL: SALARIOS CAÍDOS, DISCRIMINACIÓN Y CONCILIACIÓN ====================
  {
    id: "2027050",
    ius: "2027050",
    registroDigital: "2027050",
    rubro: "SALARIOS VENCIDOS (CAÍDOS). EL TOPE DE DOCE MESES PREVISTO EN EL ARTÍCULO 48 DE LA LEY FEDERAL DEL TRABAJO ES CONSTITUCIONAL Y NO VULNERA EL DERECHO AL TRABAJO.",
    texto: "La limitación a doce meses en el pago de salarios caídos, acompañada del pago de intereses al dos por ciento mensual capitalizable sobre quince meses de salario, supera el test de proporcionalidad constitucional al perseguir un fin legítimo consistente en evitar la quiebra prolongada de las fuentes de empleo por juicios dilatados y desincentivar tácticas procesales dilatorias.",
    precedentes: "Contradicción de criterios 340/2022. Segunda Sala. 7 de junio de 2023. Unanimidad de cuatro votos. Ponente: Ministro Javier Laynez Potisek.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Laboral",
    materias: ["Laboral", "Constitucional"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 27, Julio de 2023, Tomo II, Pág. 1540",
    clave: "2a./J. 48/2023 (11a.)",
    fechaPublicacion: "2023-07-21",
    expediente: "CC 340/2022",
    temasClave: ["salarios caidos", "salarios vencidos", "articulo 48 lft", "despido injustificado", "intereses laborales", "reinstalacion"]
  },
  {
    id: "2025800",
    ius: "2025800",
    registroDigital: "2025800",
    rubro: "CONCILIACIÓN PREJUDICIAL OBLIGATORIA EN EL NUEVO MODELO LABORAL. EXCEPCIONES EN CASOS DE DISCRIMINACIÓN, ACOSO SEXUAL Y VIOLENCIA LABORAL.",
    texto: "De conformidad con el artículo 685-Ter de la Ley Federal del Trabajo, las personas trabajadoras que demanden la reinstalación o indemnización alegando discriminación por embarazo, hostigamiento, acoso sexual o vulneración a la libertad sindical quedan exentas de agotar la etapa prejudicial obligatoria ante los Centros de Conciliación, pudiendo acudir de manera directa a los Tribunales Laborales.",
    precedentes: "Contradicción de criterios 180/2022. Segunda Sala. 9 de noviembre de 2022. Ponente: Ministra Yasmín Esquivel Mossa.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Laboral",
    materias: ["Laboral", "Procesal Laboral", "Genero"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 19, Noviembre de 2022, Tomo II, Pág. 1290",
    clave: "2a./J. 65/2022 (11a.)",
    fechaPublicacion: "2022-11-25",
    expediente: "CC 180/2022",
    temasClave: ["conciliacion laboral", "centros de conciliacion", "acoso laboral", "embarazo", "discriminacion", "juicio laboral directo"]
  },

  // ==================== MERCANTIL Y BANCARIO: CLÁUSULAS ABUSIVAS Y TRANSFERENCIAS ====================
  {
    id: "2026750",
    ius: "2026750",
    registroDigital: "2026750",
    rubro: "TRANSFERENCIAS BANCARIAS ELECTRÓNICAS NO RECONOCIDAS. LA CARGA PROBATORIA CORRESPONDE A LA INSTITUCIÓN BANCARIA CUANDO EL USUARIO ALEGA CARGOS INDEBIDOS O FRAUDE.",
    texto: "En los juicios mercantiles orales promovidos contra instituciones de banca múltiple por cargos, retiros o transferencias por internet no autorizadas por el cuentahabiente, opera la presunción en favor del usuario. La institución financiera tiene la carga estricta de acreditar mediante prueba pericial en informática forense que sus sistemas de autenticación y doble factor no fallaron y que la operación se realizó válidamente.",
    precedentes: "Contradicción de criterios 450/2022. Primera Sala. 17 de mayo de 2023. Cinco votos. Ponente: Ministro Juan Luis González Alcántara Carrancá.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Mercantil", "Bancario"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 25, Mayo de 2023, Tomo I, Pág. 920",
    clave: "1a./J. 41/2023 (11a.)",
    fechaPublicacion: "2023-05-26",
    expediente: "CC 450/2022",
    temasClave: ["transferencias no reconocidas", "fraude bancario", "banco", "carga probatoria", "pericial informatica", "banca electronica", "spei"]
  },
  {
    id: "2025250",
    ius: "2025250",
    registroDigital: "2025250",
    rubro: "CONTRATOS DE ADHESIÓN Y CLÁUSULAS ABUSIVAS EN MATERIA MERCANTIL. FACULTAD JUDICIAL PARA DECLARAR SU NULIDAD CUANDO PRODUCEN DESEQUILIBRIO DESPROPORCIONADO EN PERJUICIO DEL CONSUMIDOR.",
    texto: "Las cláusulas predispuestas unilateralmente en contratos de adhesión que impongan renuncias injustificadas a derechos procesales, trasladen riesgos operativos del proveedor al consumidor o fijen penalidades lesivas deben declararse nulas de pleno derecho por contravenir el principio de equidad contractual y el artículo 28 constitucional en materia de protección al consumidor.",
    precedentes: "Amparo directo en revisión 2190/2021. Primera Sala. 23 de marzo de 2022. Ponente: Ministro Jorge Mario Pardo Rebolledo.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Mercantil", "Consumidor"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 12, Abril de 2022, Tomo I, Pág. 540",
    clave: "1a./J. 19/2022 (11a.)",
    fechaPublicacion: "2022-04-22",
    expediente: "ADR 2190/2021",
    temasClave: ["contratos de adhesion", "clausulas abusivas", "profeco", "consumidor", "nulidad contractual", "mercantil"]
  },

  // ==================== ADMINISTRATIVO, FISCAL Y BLOQUEO DE CUENTAS ====================
  {
    id: "2027400",
    ius: "2027400",
    registroDigital: "2027400",
    rubro: "BLOQUEO DE CUENTAS BANCARIAS POR LA UNIDAD DE INTELIGENCIA FINANCIERA (UIF). ES INCONSTITUCIONAL SI OBEDECE A INVESTIGACIONES ESTRICTAMENTE NACIONALES SIN MANDATO JUDICIAL PREVIO.",
    texto: "La facultad de la Unidad de Inteligencia Financiera para incluir a personas en la lista de personas bloqueadas prevista en el artículo 115 de la Ley de Instituciones de Crédito sólo resulta constitucional cuando derive del cumplimiento de compromisos internacionales o peticiones expresas de organismos u autoridades extranjeras con facultades homólogas. El bloqueo fundado en pesquisas domésticas vulnera la garantía de seguridad jurídica y debido proceso.",
    precedentes: "Contradicción de tesis 168/2019 (Criterio Medina Mora) reiterado por la Segunda Sala en Amparo en revisión 612/2023. Ponente: Ministro Alberto Pérez Dayán.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Administrativa",
    materias: ["Administrativa", "Constitucional", "Bancario", "Fiscal"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 30, Octubre de 2023, Tomo II, Pág. 1410",
    clave: "2a./J. 70/2023 (11a.)",
    fechaPublicacion: "2023-10-20",
    expediente: "AR 612/2023",
    temasClave: ["bloqueo de cuentas", "uif", "lavado de dinero", "unidad de inteligencia financiera", "amparo indirecto", "garantia de audiencia"]
  },
  {
    id: "2026200",
    ius: "2026200",
    registroDigital: "2026200",
    rubro: "DEVOLUCIÓN DE SALDO A FAVOR DE IMPUESTOS (IVA E ISR). EL SILENCIO O RETRASO INJUSTIFICADO DEL SAT GENERA EL PAGO OBLIGATORIO DE INTERESES INDEMNIZATORIOS.",
    texto: "Cuando la autoridad fiscal omite resolver la solicitud de devolución de un saldo a favor dentro del término legal de cuarenta días previsto en el artículo 22 del Código Fiscal de la Federación, o niega indebidamente el reintegro que posteriormente es reconocido en juicio, el contribuyente tiene derecho al cobro de actualizaciones e intereses indemnizatorios calculados a partir del vencimiento del plazo.",
    precedentes: "Contradicción de criterios 310/2022. Segunda Sala. 8 de febrero de 2023. Ponente: Ministro Luis María Aguilar Morales.",
    epoca: "Undécima Época",
    instancia: "Segunda Sala",
    organoJurisdiccional: "Segunda Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Administrativa",
    materias: ["Administrativa", "Fiscal"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 22, Febrero de 2023, Tomo II, Pág. 1190",
    clave: "2a./J. 15/2023 (11a.)",
    fechaPublicacion: "2023-02-24",
    expediente: "CC 310/2022",
    temasClave: ["saldo a favor", "devolucion de impuestos", "sat", "iva", "isr", "intereses indemnizatorios", "codigo fiscal"]
  },

  // ==================== CIVIL: ARRENDAMIENTO, USUCAPIÓN Y CONTRATOS ====================
  {
    id: "2026900",
    ius: "2026900",
    registroDigital: "2026900",
    rubro: "ARRENDAMIENTO INMOBILIARIO. LA FALTA DE PAGO DE RENTAS DA DERECHO A LA RESCISIÓN Y DESOCUPACIÓN SIN QUE EL ARRENDADOR ESTÉ OBLIGADO A ACREDITAR LA PROPIEDAD DEL INMUEBLE.",
    texto: "El contrato de arrendamiento genera una relación jurídica personal y no real entre las partes contratantes. En consecuencia, en el juicio especial de desahucio o rescisión contractual por mora en el pago de pensiones rentísticas, el arrendador no necesita demostrar la propiedad del bien inmueble, siendo título suficiente la exhibición del contrato de arrendamiento respectivo.",
    precedentes: "Contradicción de criterios 140/2023. Pleno Regional en Materia Civil de la Región Centro-Sur. 11 de agosto de 2023.",
    epoca: "Undécima Época",
    instancia: "Plenos Regionales",
    organoJurisdiccional: "Pleno Regional en Materia Civil de la Región Centro-Sur",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Arrendamiento"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 28, Agosto de 2023, Tomo II, Pág. 1850",
    clave: "PR.C.CS. J/12 C (11a.)",
    fechaPublicacion: "2023-08-18",
    expediente: "CC 140/2023",
    temasClave: ["arrendamiento", "desahucio", "rentas", "inquilino", "desalojo", "contrato de arrendamiento", "mora"]
  },
  {
    id: "2025400",
    ius: "2025400",
    registroDigital: "2025400",
    rubro: "PRESCRIPCIÓN POSITIVA (USUCAPIÓN). EL POSEEDOR EN CONCEPTO DE PROPIETARIO DEBE PROBAR LA CAUSA GENERADORA DE SU POSESIÓN DE FORMA FEHACIENTE.",
    texto: "Para adquirir un bien inmueble por prescripción adquisitiva no basta el simple transcurso del tiempo en posesión material; el actor debe revelar y justificar la causa generadora de su posesión (título originario como compraventa, donación o cesión) mediante pruebas fehacientes y objetivas que demuestren que comenzó a poseer en concepto de dueño de forma pacífica, continua y pública.",
    precedentes: "Contradicción de tesis 420/2021. Primera Sala. 12 de enero de 2022. Cinco votos. Ponente: Ministra Norma Lucía Piña Hernández.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Civil",
    materias: ["Civil", "Bienes"],
    fuente: "Semanario Judicial de la Federación",
    localizacion: "Libro 10, Febrero de 2022, Tomo I, Pág. 620",
    clave: "1a./J. 4/2022 (11a.)",
    fechaPublicacion: "2022-02-11",
    expediente: "CT 420/2021",
    temasClave: ["prescripcion positiva", "usucapion", "posesion", "causa generadora", "propiedad", "inmuebles"]
  },

  // ==================== AMPARO: SUPLENCIA DE LA QUEJA Y RECURSO DE REVISIÓN ====================
  {
    id: "2026400",
    ius: "2026400",
    registroDigital: "2026400",
    rubro: "SUPLENCIA DE LA QUEJA DEFICIENTE EN EL JUICIO DE AMPARO. OPERA DE FORMA AMPLIA Y OBLIGATORIA EN FAVOR DE PERSONAS DE COMUNIDADES INDÍGENAS Y GRUPOS VULNERABLES.",
    texto: "De conformidad con el artículo 79 de la Ley de Amparo, el órgano jurisdiccional está obligado a suplir la deficiencia de los conceptos de violación o de los agravios en favor de pueblos y comunidades indígenas o afromexicanas, así como de personas en extrema vulnerabilidad económica o social, incluso ante la ausencia total de conceptos de violación en la demanda o recurso.",
    precedentes: "Amparo directo en revisión 1980/2022. Primera Sala. 19 de abril de 2023. Ponente: Ministro Alfredo Gutiérrez Ortiz Mena.",
    epoca: "Undécima Época",
    instancia: "Primera Sala",
    organoJurisdiccional: "Primera Sala de la Suprema Corte de Justicia de la Nación",
    tipoTesis: "Jurisprudencia",
    materia: "Común",
    materias: ["Común", "Constitucional", "Derechos Humanos"],
    fuente: "Gaceta del Semanario Judicial de la Federación",
    localizacion: "Libro 24, Abril de 2023, Tomo I, Pág. 420",
    clave: "1a./J. 31/2023 (11a.)",
    fechaPublicacion: "2023-04-28",
    expediente: "ADR 1980/2022",
    temasClave: ["suplencia de la queja", "comunidades indigenas", "vulnerabilidad", "amparo directo", "amparo indirecto", "tutela judicial"]
  }
];
